project_id = "gwpspvocwffkabdftmoo"

[functions.update-points]
verify_jwt = false

[functions.health-agent]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.location-restaurants]
verify_jwt = false

[functions.recipe-agent]
verify_jwt = false
